# generated by datamodel-codegen:
#   filename:  medications.json
#   timestamp: 2023-03-23T20:36:04+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class AceInhibitor(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class AntianginalItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class Anticoagulant(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class BetaBlockerItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class DiureticItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class MineralItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    strength: str
    dose: str
    route: str
    sig: str
    pill_count: str = Field(..., alias='pillCount')
    refills: str


class Medication(BaseModel):
    class Config:
        allow_population_by_field_name = True

    ace_inhibitors: List[AceInhibitor] = Field(..., alias='aceInhibitors')
    antianginal: List[AntianginalItem]
    anticoagulants: List[Anticoagulant]
    beta_blocker: List[BetaBlockerItem] = Field(..., alias='betaBlocker')
    diuretic: List[DiureticItem]
    mineral: List[MineralItem]


class Lab(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    time: str
    location: str


class ImagingItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: str
    time: str
    location: str


class BaseMedications(BaseModel):
    class Config:
        allow_population_by_field_name = True

    medications: List[Medication]
    labs: List[Lab]
    imaging: List[ImagingItem]
