# generated by datamodel-codegen:
#   filename:  donut.json
#   timestamp: 2023-03-23T20:36:03+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class BatterItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: str
    type: str


class Batters(BaseModel):
    class Config:
        allow_population_by_field_name = True

    batter: List[BatterItem]


class ToppingItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: str
    type: str


class BaseDonut(BaseModel):
    class Config:
        allow_population_by_field_name = True

    id: str
    type: str
    name: str
    ppu: float
    batters: Batters
    topping: List[ToppingItem]
